footprint: [ [0.3602, -0.0708], [0.274, -0.0708], [0.274, -0.254], [-0.274, -0.274], [-0.274, 0.274], [0.274, 0.274], [0.274, 0.0708], [0.3602, 0.0708] ]
footprint_padding: 0.1
transform_tolerance: 0.5
map_type: costmap
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: hokuyo_frame, data_type: LaserScan, topic: hokuyo, marking: true, clearing: true, raytrace_range: 7.5, obstacle_range: 6.5}
track_unknown_space: true
inflation_radius: 1.8
cost_scaling_factor: 2.5
